# Generated by Django 4.0.5 on 2022-08-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='eventDetails',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
